repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--line-length, '100']
    types: [python]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
    types: [python]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.2
  hooks:
  - id: clang-format
